---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: OrganizationManufacturer
  data:
    - name: Arista
      description: Arista Networks
    - name: Cisco
      description: Cisco Systems
    - name: Juniper
      description: Juniper Networks
    - name: Nokia
      description: Nokia
    - name: Versa Networks
      description: Versa Networks
