---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: LocationRegion
  data:
    - name: EMEA
      shortname: emea
      description: Europe, Middle East, Africa region.

---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: LocationSite
  data:
    - name: London
      shortname: lon
      description: London PoP.
      parent: emea
    - name: Frankfurt
      shortname: fra
      description: Frankfurt PoP.
      parent: emea
    - name: Amsterdam
      shortname: ams
      description: Amsterdam PoP.
      parent: emea
    - name: Paris
      shortname: par
      description: Paris PoP.
      parent: emea
