query PeInterfaceAlloc {
  ServiceL3VpnSite {
    edges {
      node {
        name { value }
        pe_device { node { name { value } } }
        pe_interface { node { id name { value } } }
      }
    }
  }
}
